# Generated by Django 3.1.7 on 2021-04-07 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='work_image')),
                ('work_content', models.CharField(max_length=200)),
                ('work_link', models.URLField()),
            ],
        ),
    ]
