# Generated by Django 3.1.7 on 2021-04-06 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='image',
            field=models.ImageField(default='photo_2019-10-25_23-16-15.jpg', upload_to='author_image'),
        ),
    ]
